// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FT.Lib.Data.Database.FerreTodo;

public partial class Producto
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public int UbicacionId { get; set; }

    public int TipoVentaId { get; set; }

    public string Descripcion { get; set; }

    public string Codigo { get; set; }

    public string Marca { get; set; }

    public string Serie { get; set; }

    public string Modelo { get; set; }

    public bool Disponible { get; set; }

    public DateTime FechaIngreso { get; set; }

    public int CantidadDisponible { get; set; }

    public bool Estado { get; set; }

    public virtual Ubicacion Ubicacion { get; set; }
}