// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FT.Lib.Data.Database.FerreTodo;

public partial class ProductoIngresoDetalle
{
    public int Id { get; set; }

    public int TipoPagoId { get; set; }

    public string Proveedor { get; set; }

    public string FacturaIngreso { get; set; }

    public string Plazo { get; set; }

    public decimal Impuesto { get; set; }

    public decimal PrecioTotal { get; set; }
}