// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FT.Lib.Data.Database.FerreTodo;

public partial class ProductoIngreso
{
    public int Id { get; set; }

    public int ProductoIngresoDetalleId { get; set; }

    public DateTime FechaIn { get; set; }

    public string Descripcion { get; set; }

    public int UbicacionId { get; set; }

    public int Cantidad { get; set; }

    public decimal Costo { get; set; }
}