// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FT.Lib.Data.Database.FerreTodo;

public partial class Usuario
{
    public int Id { get; set; }

    public int TipoIdentificacionId { get; set; }

    public int TipoUsuarioId { get; set; }

    public Guid Guid { get; set; }

    public string Identificacion { get; set; }

    public string Nombre { get; set; }

    public string Apellido1 { get; set; }

    public string Apellido2 { get; set; }

    public string Email { get; set; }

    public string Celular { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public DateTime FechaIn { get; set; }

    public int UsuarioIn { get; set; }

    public bool Estado { get; set; }

    public bool CambiarPass { get; set; }
}