// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FT.Lib.Data.Database.FerreTodo;

public partial class TipoUsuario
{
    public int Id { get; set; }

    public string Descripcion { get; set; }
}