// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FT.Lib.Data.Database.FerreTodo;

public partial class Ubicacion
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public bool Estado { get; set; }

    public virtual ICollection<Producto> Producto { get; set; } = new List<Producto>();
}